### ISSUE TITLE
Not listing credentials

### ISSUE THREAD

**Issue by nibblesnbits** [jenkinsci/aws-beanstalk-publisher-plugin#10]
After adding my AWS credentials in Jenkins, I tried to add the step to my configuration, but the dropdown for credentials contains no items.  I've tried restarting Jenkins and reloading the configuration from disk, but to no avail.

**Comment by DavidTanner** [comment]
The plugin isn't using credentials. You will need to set up some custom credentials on the jenkins configuration page

**Comment by nibblesnbits** [comment]
I actually just found that seconds before you responded.  sorry about that.

**Comment by DavidTanner** [comment]
No worries.

**Comment by nibblesnbits** [comment]
I do have another issue, though.

```
Environment found (environment id='e-tmmr2pry4j', name='MyApp-test'). Attempting to update environment to version label 'v20150701140343'
'Picard-test': Attempt 0/5
'Picard-test': Problem:
com.amazonaws.AmazonServiceException: No Application Version named 'v20150701140343' found. (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 3f993b47-1ffa-11e5-a511-5fd992922954)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1160)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:748)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:2014)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.updateEnvironment(AWSElasticBeanstalkClient.java:1519)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.updateEnv(AWSEBEnvironmentUpdaterThread.java:81)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.run(AWSEBEnvironmentUpdaterThread.java:214)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.call(AWSEBEnvironmentUpdaterThread.java:184)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.call(AWSEBEnvironmentUpdaterThread.java:20)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
'MyApp-test': Was updated, but couldn't be verified!
Finished: FAILURE
Build step 'Deploy into AWS Elastic Beanstalk' changed build result to FAILURE
Build step 'Deploy into AWS Elastic Beanstalk' marked build as failure
Finished: FAILURE
```

For some reason AWS won't accept my version.

**Comment by DavidTanner** [comment]
The version has to exist before it can update it.  You can use the S3 uploader to upload a local file and tie it to your EB instance.  Once the version is tied to EB, then you don't have to do the S3 upload.

**Comment by nibblesnbits** [comment]
Then I'm lost on what this plugin accomplishes.  If I can't push code to AWS with it, where do I go to do that?

**Comment by nibblesnbits** [comment]
So I got everything working, but it seems to me that the operations are done out of order.

```
D:\Jenkins\MyApp>exit 0 
Environment found (environment id='e-tmmr2pry4j', name='MyApp-test'). Attempting to update environment to version label '20150701181149'
'MyApp-test': Attempt 0/5
'MyApp-test': Problem:
com.amazonaws.AmazonServiceException: No Application Version named '20150701181149' found. (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: c96068fc-201c-11e5-bbf4-db8606f30acf)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1160)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:748)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:2014)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.updateEnvironment(AWSElasticBeanstalkClient.java:1519)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.updateEnv(AWSEBEnvironmentUpdaterThread.java:81)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.run(AWSEBEnvironmentUpdaterThread.java:214)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.call(AWSEBEnvironmentUpdaterThread.java:184)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.call(AWSEBEnvironmentUpdaterThread.java:20)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
'MyApp-test': Was updated, but couldn't be verified!
Finished: SUCCESS
Zipping contents of Root File Object (builds) into tmp file awseb-8804638276368732907.zip (includes=, excludes=)
Uploading file awseb-8804638276368732907.zip as s3://elasticbeanstalk-us-west-2-728945641667/MyApp/MyApp-20150701181149.zip
Creating application version 20150701181149 for application MyApp for path s3://elasticbeanstalk-us-west-2-728945641667/MyApp/MyApp-20150701181149.zip
Environment found (environment id='e-tmmr2pry4j', name='MyApp-test'). Attempting to update environment to version label '20150701181149'
'MyApp-test': Attempt 0/5
'MyApp-test': EVENT [2015-07-01 18:12:55 UTC+0000] (INFO) Environment update is starting.
'MyApp-test': Waiting for update to finish. Status: Updating
'MyApp-test': Pausing update for 30 seconds
'MyApp-test': EVENT [2015-07-01 18:12:58 UTC+0000] (INFO) Deploying new version to instance(s).
'MyApp-test': EVENT [2015-07-01 18:13:05 UTC+0000] (WARN) Deployment package did not contain an iisApp
'MyApp-test': EVENT [2015-07-01 18:13:05 UTC+0000] (ERROR) Deployment Failed: Unexpected Exception
'MyApp-test': EVENT [2015-07-01 18:13:05 UTC+0000] (INFO) Started Application Update
'MyApp-test': EVENT [2015-07-01 18:13:05 UTC+0000] (ERROR) Error occurred during build: Command hooks failed
'MyApp-test': EVENT [2015-07-01 18:13:13 UTC+0000] (ERROR) [Instance: i-ac29d964 ConfigSet: Infra-WriteRuntimeConfig, Infra-WriteApplication1, Infra-WriteApplication2, Infra-EmbeddedPreBuild, Hook-PreAppDeploy, Hook-EnactAppDeploy, Infra-EmbeddedPostBuild, Hook-PostAppDeploy] Command failed on instance. Return code: 1 Output: null.
'MyApp-test': EVENT [2015-07-01 18:13:13 UTC+0000] (INFO) Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
'MyApp-test': EVENT [2015-07-01 18:13:15 UTC+0000] (INFO) New application version was deployed to running EC2 instances.
'MyApp-test': EVENT [2015-07-01 18:13:15 UTC+0000] (ERROR) Update environment operation is complete, but with errors. For more information, see troubleshooting documentation.
'MyApp-test': Updated!
'MyApp-test': Current version is:'20150701181149'
'MyApp-test': Update was successful
'MyApp-test': Completed successfully.
Finished: SUCCESS
Finished: SUCCESS
```

The process does the deployment correctly, but it seems like (from the output) that the S3 operation should be performed first.

**Comment by DavidTanner** [comment]
That looks like you have a build step and a post build step

**Comment by DavidTanner** [comment]
You have to do the s3 upload in the same step, or before, the plugin runs.

**Comment by nibblesnbits** [comment]
I don't know how I missed that.  Now everything works as expected.  Thank you.

**Comment by itsovereasy** [comment]
Can some one help on this im getting an error like this



No credentials provided for build!!!
No credentials provided for build!!!
Root File Object is a file. We assume its a zip file, which is okay.
Uploading file awseb-9016416424721480451.zip as s3://elasticbeanstalk-us-west-2-565561526804/application-2b687dfebd2c0a30c4138954c69b5b6aa109ac83-jenkins-yourdemo-17.zip
Creating application version 2b687dfebd2c0a30c4138954c69b5b6aa109ac83-jenkins-yourdemo-17 for application application for path s3://elasticbeanstalk-us-west-2-565561526804/application-2b687dfebd2c0a30c4138954c69b5b6aa109ac83-jenkins-yourdemo-17.zip
ERROR: Build step failed with exception
com.amazonaws.AmazonServiceException: User: arn:aws:sts::565561526804:assumed-role/aws-elasticbeanstalk-ec2-role/i-08324fd07b28bc1f6 is not authorized to perform: elasticbeanstalk:CreateApplicationVersion on resource: arn:aws:elasticbeanstalk:us-west-2:565561526804:applicationversion/application/2b687dfebd2c0a30c4138954c69b5b6aa109ac83-jenkins-yourdemo-17 (Service: AWSElasticBeanstalk; Status Code: 403; Error Code: AccessDenied; Request ID: 0a568d22-5c9b-11e7-991a-057fbe6d08c5)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.doInvoke(AWSElasticBeanstalkClient.java:2223)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:2193)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createApplicationVersion(AWSElasticBeanstalkClient.java:596)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBS3Uploader.createApplicationVersion(AWSEBS3Uploader.java:150)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBS3Uploader.uploadArchive(AWSEBS3Uploader.java:120)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdater.perform(AWSEBEnvironmentUpdater.java:66)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBElasticBeanstalkSetup.perform(AWSEBElasticBeanstalkSetup.java:174)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:22)
Caused: java.lang.RuntimeException

**Comment by vikram291194** [comment]
Hello,
I too am facing the same issue. please refer the below image
![image](https://user-images.githubusercontent.com/82135939/159427109-50811411-262b-42a5-8b42-5f9c3e354968.png)




Can you please help me in figuring out what config. needs to be done?
I have given S3 full access and AWS CodePipeline full access to my EC2 server and also Attached the proper bucket policy to my S3 bucket i.e with the proper Elastic Beanstalk role.
i have also added proper credentials in AWS Elastic Beanstalk plugin in Jenkins and also stored my AWS account credentials in Jenkins.
