### ISSUE TITLE
Environment name never saving

### ISSUE THREAD

**Issue by cthorne66** [jenkinsci/aws-beanstalk-publisher-plugin#11]
Every time I save the job config, and try to execute, I get this:

![image](https://cloud.githubusercontent.com/assets/2610325/8578775/5971bf20-2576-11e5-993d-fa4a16c0cfc5.png)

When re-opening the job configuration, I can see that that environment name never gets saved, no matter how many times i add or look it up.

**Comment by cthorne66** [comment]
Using version 1.4.4, on Linux machine with Jenkins 1.510.

**Comment by DavidTanner** [comment]
Are there other errors in the log?  That just doesn't make any sense.

**Comment by DavidTanner** [comment]
From every source I can find, a DescribableList is a list.

**Comment by cthorne66** [comment]
Here is what I could see in the Jenkins system log

Jul 8, 2015 1:19:26 PM org.kohsuke.stapler.compression.CompressionFilter reportException
WARNING: Untrapped servlet exception
javax.servlet.ServletException: java.lang.NoSuchMethodError: hudson.util.DescribableList.add(Ljava/lang/Object;)Z
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:719)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:770)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:241)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:677)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:770)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:241)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:677)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:770)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:583)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:214)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:95)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:179)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:86)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:84)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:98)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:98)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.NoSuchMethodError: hudson.util.DescribableList.add(Ljava/lang/Object;)Z
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBElasticBeanstalkSetup.<init>(AWSEBElasticBeanstalkSetup.java:68)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.kohsuke.stapler.RequestImpl.invokeConstructor(RequestImpl.java:438)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:76)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:594)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:632)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:391)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:588)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:391)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:387)
	at hudson.model.Descriptor.newInstance(Descriptor.java:593)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:941)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:926)
	at hudson.util.DescribableList.rebuildHetero(DescribableList.java:203)
	at hudson.model.Project.submit(Project.java:200)
	at hudson.model.Job.doConfigSubmit(Job.java:1076)
	at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:753)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:288)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:151)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:90)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:111)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:677)
	... 50 more

**Comment by DavidTanner** [comment]
There is something more going on here. Can you update your jenkins version?

**Comment by cthorne66** [comment]
Unfortunately I cannot, since it's a shared instance across multiple applications.  However, I did install a new version of Jenkins on my local machine and was able to use this plugin without issue.  Hopefully no one else has this issue on an older install of Jenkins.

Thank you for looking into
