### ISSUE TITLE
Deploying using Instance Profile not working

### ISSUE THREAD

**Issue by tchdp** [jenkinsci/aws-beanstalk-publisher-plugin#20]
If I leave the credentials blank in the plugin to use the instance profile, when I run the job, I get a NullPointerException - Stack trace is below. Looks like the S3 Client is not using the instance profile.

```
No credentials provided for build!!!
No credentials provided for build!!!
ERROR: Build step failed with exception
java.lang.RuntimeException: java.lang.NullPointerException
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:25)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBBuilder.perform(AWSEBBuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.Build$BuildExecution.build(Build.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.lang.NullPointerException
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBUtils.getS3(AWSEBUtils.java:52)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBS3Uploader.uploadArchive(AWSEBS3Uploader.java:74)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdater.perform(AWSEBEnvironmentUpdater.java:66)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBElasticBeanstalkSetup.perform(AWSEBElasticBeanstalkSetup.java:174)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:21)
	... 10 more
Build step 'Deploy into AWS Elastic Beanstalk' marked build as failure
```

**Comment by DavidTanner** [comment]
Fixed in 1.5.5
