### ISSUE TITLE
sleep interrupted

### ISSUE THREAD

**Issue by eliranshlomo** [jenkinsci/aws-beanstalk-publisher-plugin#23]
Hi,

my last few jobs failed due to sleep interrupted exception 

ERROR: Build step failed with exception
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.run(AWSEBEnvironmentUpdaterThread.java:220)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.call(AWSEBEnvironmentUpdaterThread.java:185)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdaterThread.call(AWSEBEnvironmentUpdaterThread.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.lang.InterruptedException
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:25)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBBuilder.perform(AWSEBBuilder.java:65)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.run(BuildStepRunner.java:110)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$Fail.conditionalRun(BuildStepRunner.java:154)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
	at org.jenkinsci.plugins.conditionalbuildstep.singlestep.SingleConditionalBuilder.perform(SingleConditionalBuilder.java:108)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:244)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdater.updateEnvironments(AWSEBEnvironmentUpdater.java:105)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdater.perform(AWSEBEnvironmentUpdater.java:70)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBElasticBeanstalkSetup.perform(AWSEBElasticBeanstalkSetup.java:174)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:21)
	... 14 more
Build step 'Conditional step (single)' marked build as failure

did someone had those issues also?

**Comment by DavidTanner** [comment]
Please check 1.6.0
