### ISSUE TITLE
Deployment fails when bucket region is not set

### ISSUE THREAD

**Issue by michaelwiles** [jenkinsci/aws-beanstalk-publisher-plugin#34]
I upgraded to 1.7.1 and my deployment now fails with the following stack trace:

FATAL: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:25)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBBuilder.perform(AWSEBBuilder.java:65)
	at hudson.plugins.promoted_builds.Promotion$RunnerImpl.build(Promotion.java:405)
	at hudson.plugins.promoted_builds.Promotion$RunnerImpl.doRun(Promotion.java:347)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.Run.run(Run.java:1679)
	at hudson.plugins.promoted_builds.Promotion.run(Promotion.java:286)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.lang.NullPointerException
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBS3Uploader.uploadArchive(AWSEBS3Uploader.java:77)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.AWSEBEnvironmentUpdater.perform(AWSEBEnvironmentUpdater.java:66)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBElasticBeanstalkSetup.perform(AWSEBElasticBeanstalkSetup.java:174)
	at org.jenkinsci.plugins.awsbeanstalkpublisher.extensions.AWSEBSetup.perform(AWSEBSetup.java:21)
	... 9 more

I have tracked this down to the following lines:

```
   if(this.bucketRegion.isEmpty())     //this is where the NPE occurs (because bucketRegion is null)
          s3 = AWSEBUtils.getS3(credentials, awsRegion);
   } else {
          s3 = AWSEBUtils.getS3(credentials, Regions.fromName(bucketRegion));
   }

```
I assume that because the bucket region is a new field it is not yet specified in my config and although there is a check for it being empty, there is no check for it being null.

This `if(this.bucketRegion.isEmpty())` needs to change to `if(this.bucketRegion == null || this.bucketRegion.isEmpty())`

**Comment by michaelwiles** [comment]
I'll do some testing and if I'm happy submit a pull request

**Comment by DavidTanner** [comment]
You might just wrap it using the string utility .isEmpty

**Comment by michaelwiles** [comment]
Good idea, though once I'd made the change I got a different error... Will need to do more trouble shooting
