### ISSUE TITLE
AWS credential not populating

### ISSUE THREAD

**Issue by kh77** [jenkinsci/aws-beanstalk-publisher-plugin#41]
java.io.IOException: Deployment Failure
00:59:04 	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentBuilder.perform(AWSEBDeploymentBuilder.java:197)
00:59:04 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
00:59:04 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
00:59:04 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
00:59:04 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.build(MavenModuleSetBuild.java:945)
00:59:04 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:896)
00:59:04 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
00:59:04 	at hudson.model.Run.execute(Run.java:1737)
00:59:04 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
00:59:04 	at hudson.model.ResourceController.execute(ResourceController.java:97)
00:59:04 	at hudson.model.Executor.run(Executor.java:421)
00:59:04 Caused by: javax.security.auth.login.CredentialNotFoundException: aws_key_data
00:59:04 	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSClientFactory.lookupNamedCredential(AWSClientFactory.java:116)
00:59:04 	at br.com.ingenieux.jenkins.plugins.awsebdeployment.DeployerRunner.perform(DeployerRunner.java:64)
00:59:04 	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentBuilder.perform(AWSEBDeploymentBuilder.java:193)
00:59:04 	... 10 more
00:59:05 Started calculate disk usage of build
00:59:05 Finished Calculation of disk usage of build in 0 seconds
00:59:05 Started calculate disk usage of workspace
00:59:06 Finished Calculation of disk usage of workspace in  1 second
00:59:06 Finished: FAILURE

**Comment by byeddula** [comment]
hello i got the same problem how did you solve the issue
